{"name": "Нельзя войти с неверным логином(email)", "status": "passed", "start": 1709220802263, "stop": 1709220803004, "uuid": "66db6e14-f676-49fd-af74-638ea8b5990c", "historyId": "a3cf656949f525d0436d1732b8269e9b", "testCaseId": "a3cf656949f525d0436d1732b8269e9b", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_email_not_completed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-JPR4DQM"}, {"name": "thread", "value": "12320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}